apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-premium
  volumeName: azurefile
  resources:
    requests:
      storage: 100Gi