name: Actions Runner on AKS
on:
  workflow_dispatch: {
    inputs: {
      arc_runner_set_name: {
        description: 'The name of the Arc Runner Set',
        required: true,
        default: 'arc-runner-set'
      }
    }
  }

jobs:
  build:
    runs-on: ${{ inputs.arc_runner_set_name}}
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
      NUGET_PACKAGES: "./.nuget/packages"
      #DOTNET_INSTALL_DIR: "${{ github.workspace }}/.dotnet"      
      #NUGET_PACKAGES: "${{ github.workspace }}/.nuget/packages"  
    steps:
        - uses: actions/checkout@v4
        - name: Install cURL Headers
          run: |
            sudo apt-get update
            sudo apt-get -y install curl            
        - name: list nuget packages
          run: ls ~/_work/.nuget/packages/
          shell: bash            
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
        - name: Restore .NET app
          run: dotnet build azurefiles-actions-aks.csproj
